// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ortools/constraint_solver/routing_parameters.proto

#ifndef PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto
#define PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "ortools/constraint_solver/routing_enums.pb.h"
#include "ortools/constraint_solver/solver_parameters.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto 

namespace protobuf_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[3];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto
namespace operations_research {
class RoutingModelParameters;
class RoutingModelParametersDefaultTypeInternal;
extern RoutingModelParametersDefaultTypeInternal _RoutingModelParameters_default_instance_;
class RoutingSearchParameters;
class RoutingSearchParametersDefaultTypeInternal;
extern RoutingSearchParametersDefaultTypeInternal _RoutingSearchParameters_default_instance_;
class RoutingSearchParameters_LocalSearchNeighborhoodOperators;
class RoutingSearchParameters_LocalSearchNeighborhoodOperatorsDefaultTypeInternal;
extern RoutingSearchParameters_LocalSearchNeighborhoodOperatorsDefaultTypeInternal _RoutingSearchParameters_LocalSearchNeighborhoodOperators_default_instance_;
}  // namespace operations_research
namespace google {
namespace protobuf {
template<> ::operations_research::RoutingModelParameters* Arena::CreateMaybeMessage<::operations_research::RoutingModelParameters>(Arena*);
template<> ::operations_research::RoutingSearchParameters* Arena::CreateMaybeMessage<::operations_research::RoutingSearchParameters>(Arena*);
template<> ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* Arena::CreateMaybeMessage<::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace operations_research {

// ===================================================================

class RoutingSearchParameters_LocalSearchNeighborhoodOperators : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators) */ {
 public:
  RoutingSearchParameters_LocalSearchNeighborhoodOperators();
  virtual ~RoutingSearchParameters_LocalSearchNeighborhoodOperators();

  RoutingSearchParameters_LocalSearchNeighborhoodOperators(const RoutingSearchParameters_LocalSearchNeighborhoodOperators& from);

  inline RoutingSearchParameters_LocalSearchNeighborhoodOperators& operator=(const RoutingSearchParameters_LocalSearchNeighborhoodOperators& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingSearchParameters_LocalSearchNeighborhoodOperators(RoutingSearchParameters_LocalSearchNeighborhoodOperators&& from) noexcept
    : RoutingSearchParameters_LocalSearchNeighborhoodOperators() {
    *this = ::std::move(from);
  }

  inline RoutingSearchParameters_LocalSearchNeighborhoodOperators& operator=(RoutingSearchParameters_LocalSearchNeighborhoodOperators&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingSearchParameters_LocalSearchNeighborhoodOperators& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoutingSearchParameters_LocalSearchNeighborhoodOperators* internal_default_instance() {
    return reinterpret_cast<const RoutingSearchParameters_LocalSearchNeighborhoodOperators*>(
               &_RoutingSearchParameters_LocalSearchNeighborhoodOperators_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(RoutingSearchParameters_LocalSearchNeighborhoodOperators* other);
  friend void swap(RoutingSearchParameters_LocalSearchNeighborhoodOperators& a, RoutingSearchParameters_LocalSearchNeighborhoodOperators& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingSearchParameters_LocalSearchNeighborhoodOperators* New() const final {
    return CreateMaybeMessage<RoutingSearchParameters_LocalSearchNeighborhoodOperators>(NULL);
  }

  RoutingSearchParameters_LocalSearchNeighborhoodOperators* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoutingSearchParameters_LocalSearchNeighborhoodOperators>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoutingSearchParameters_LocalSearchNeighborhoodOperators& from);
  void MergeFrom(const RoutingSearchParameters_LocalSearchNeighborhoodOperators& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoutingSearchParameters_LocalSearchNeighborhoodOperators* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool use_relocate = 1;
  void clear_use_relocate();
  static const int kUseRelocateFieldNumber = 1;
  bool use_relocate() const;
  void set_use_relocate(bool value);

  // bool use_relocate_pair = 2;
  void clear_use_relocate_pair();
  static const int kUseRelocatePairFieldNumber = 2;
  bool use_relocate_pair() const;
  void set_use_relocate_pair(bool value);

  // bool use_relocate_neighbors = 3;
  void clear_use_relocate_neighbors();
  static const int kUseRelocateNeighborsFieldNumber = 3;
  bool use_relocate_neighbors() const;
  void set_use_relocate_neighbors(bool value);

  // bool use_exchange = 4;
  void clear_use_exchange();
  static const int kUseExchangeFieldNumber = 4;
  bool use_exchange() const;
  void set_use_exchange(bool value);

  // bool use_cross = 5;
  void clear_use_cross();
  static const int kUseCrossFieldNumber = 5;
  bool use_cross() const;
  void set_use_cross(bool value);

  // bool use_cross_exchange = 6;
  void clear_use_cross_exchange();
  static const int kUseCrossExchangeFieldNumber = 6;
  bool use_cross_exchange() const;
  void set_use_cross_exchange(bool value);

  // bool use_two_opt = 7;
  void clear_use_two_opt();
  static const int kUseTwoOptFieldNumber = 7;
  bool use_two_opt() const;
  void set_use_two_opt(bool value);

  // bool use_or_opt = 8;
  void clear_use_or_opt();
  static const int kUseOrOptFieldNumber = 8;
  bool use_or_opt() const;
  void set_use_or_opt(bool value);

  // bool use_lin_kernighan = 9;
  void clear_use_lin_kernighan();
  static const int kUseLinKernighanFieldNumber = 9;
  bool use_lin_kernighan() const;
  void set_use_lin_kernighan(bool value);

  // bool use_tsp_opt = 10;
  void clear_use_tsp_opt();
  static const int kUseTspOptFieldNumber = 10;
  bool use_tsp_opt() const;
  void set_use_tsp_opt(bool value);

  // bool use_make_active = 11;
  void clear_use_make_active();
  static const int kUseMakeActiveFieldNumber = 11;
  bool use_make_active() const;
  void set_use_make_active(bool value);

  // bool use_relocate_and_make_active = 21;
  void clear_use_relocate_and_make_active();
  static const int kUseRelocateAndMakeActiveFieldNumber = 21;
  bool use_relocate_and_make_active() const;
  void set_use_relocate_and_make_active(bool value);

  // bool use_make_inactive = 12;
  void clear_use_make_inactive();
  static const int kUseMakeInactiveFieldNumber = 12;
  bool use_make_inactive() const;
  void set_use_make_inactive(bool value);

  // bool use_make_chain_inactive = 13;
  void clear_use_make_chain_inactive();
  static const int kUseMakeChainInactiveFieldNumber = 13;
  bool use_make_chain_inactive() const;
  void set_use_make_chain_inactive(bool value);

  // bool use_swap_active = 14;
  void clear_use_swap_active();
  static const int kUseSwapActiveFieldNumber = 14;
  bool use_swap_active() const;
  void set_use_swap_active(bool value);

  // bool use_extended_swap_active = 15;
  void clear_use_extended_swap_active();
  static const int kUseExtendedSwapActiveFieldNumber = 15;
  bool use_extended_swap_active() const;
  void set_use_extended_swap_active(bool value);

  // bool use_node_pair_swap_active = 20;
  void clear_use_node_pair_swap_active();
  static const int kUseNodePairSwapActiveFieldNumber = 20;
  bool use_node_pair_swap_active() const;
  void set_use_node_pair_swap_active(bool value);

  // bool use_path_lns = 16;
  void clear_use_path_lns();
  static const int kUsePathLnsFieldNumber = 16;
  bool use_path_lns() const;
  void set_use_path_lns(bool value);

  // bool use_full_path_lns = 17;
  void clear_use_full_path_lns();
  static const int kUseFullPathLnsFieldNumber = 17;
  bool use_full_path_lns() const;
  void set_use_full_path_lns(bool value);

  // bool use_tsp_lns = 18;
  void clear_use_tsp_lns();
  static const int kUseTspLnsFieldNumber = 18;
  bool use_tsp_lns() const;
  void set_use_tsp_lns(bool value);

  // bool use_inactive_lns = 19;
  void clear_use_inactive_lns();
  static const int kUseInactiveLnsFieldNumber = 19;
  bool use_inactive_lns() const;
  void set_use_inactive_lns(bool value);

  // @@protoc_insertion_point(class_scope:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool use_relocate_;
  bool use_relocate_pair_;
  bool use_relocate_neighbors_;
  bool use_exchange_;
  bool use_cross_;
  bool use_cross_exchange_;
  bool use_two_opt_;
  bool use_or_opt_;
  bool use_lin_kernighan_;
  bool use_tsp_opt_;
  bool use_make_active_;
  bool use_relocate_and_make_active_;
  bool use_make_inactive_;
  bool use_make_chain_inactive_;
  bool use_swap_active_;
  bool use_extended_swap_active_;
  bool use_node_pair_swap_active_;
  bool use_path_lns_;
  bool use_full_path_lns_;
  bool use_tsp_lns_;
  bool use_inactive_lns_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoutingSearchParameters : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.RoutingSearchParameters) */ {
 public:
  RoutingSearchParameters();
  virtual ~RoutingSearchParameters();

  RoutingSearchParameters(const RoutingSearchParameters& from);

  inline RoutingSearchParameters& operator=(const RoutingSearchParameters& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingSearchParameters(RoutingSearchParameters&& from) noexcept
    : RoutingSearchParameters() {
    *this = ::std::move(from);
  }

  inline RoutingSearchParameters& operator=(RoutingSearchParameters&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingSearchParameters& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoutingSearchParameters* internal_default_instance() {
    return reinterpret_cast<const RoutingSearchParameters*>(
               &_RoutingSearchParameters_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(RoutingSearchParameters* other);
  friend void swap(RoutingSearchParameters& a, RoutingSearchParameters& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingSearchParameters* New() const final {
    return CreateMaybeMessage<RoutingSearchParameters>(NULL);
  }

  RoutingSearchParameters* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoutingSearchParameters>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoutingSearchParameters& from);
  void MergeFrom(const RoutingSearchParameters& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoutingSearchParameters* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef RoutingSearchParameters_LocalSearchNeighborhoodOperators LocalSearchNeighborhoodOperators;

  // accessors -------------------------------------------------------

  // .operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators local_search_operators = 3;
  bool has_local_search_operators() const;
  void clear_local_search_operators();
  static const int kLocalSearchOperatorsFieldNumber = 3;
  private:
  const ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators& _internal_local_search_operators() const;
  public:
  const ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators& local_search_operators() const;
  ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* release_local_search_operators();
  ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* mutable_local_search_operators();
  void set_allocated_local_search_operators(::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* local_search_operators);

  // .operations_research.FirstSolutionStrategy.Value first_solution_strategy = 1;
  void clear_first_solution_strategy();
  static const int kFirstSolutionStrategyFieldNumber = 1;
  ::operations_research::FirstSolutionStrategy_Value first_solution_strategy() const;
  void set_first_solution_strategy(::operations_research::FirstSolutionStrategy_Value value);

  // .operations_research.LocalSearchMetaheuristic.Value local_search_metaheuristic = 4;
  void clear_local_search_metaheuristic();
  static const int kLocalSearchMetaheuristicFieldNumber = 4;
  ::operations_research::LocalSearchMetaheuristic_Value local_search_metaheuristic() const;
  void set_local_search_metaheuristic(::operations_research::LocalSearchMetaheuristic_Value value);

  // double guided_local_search_lambda_coefficient = 5;
  void clear_guided_local_search_lambda_coefficient();
  static const int kGuidedLocalSearchLambdaCoefficientFieldNumber = 5;
  double guided_local_search_lambda_coefficient() const;
  void set_guided_local_search_lambda_coefficient(double value);

  // int64 optimization_step = 7;
  void clear_optimization_step();
  static const int kOptimizationStepFieldNumber = 7;
  ::google::protobuf::int64 optimization_step() const;
  void set_optimization_step(::google::protobuf::int64 value);

  // int64 solution_limit = 8;
  void clear_solution_limit();
  static const int kSolutionLimitFieldNumber = 8;
  ::google::protobuf::int64 solution_limit() const;
  void set_solution_limit(::google::protobuf::int64 value);

  // int64 time_limit_ms = 9;
  void clear_time_limit_ms();
  static const int kTimeLimitMsFieldNumber = 9;
  ::google::protobuf::int64 time_limit_ms() const;
  void set_time_limit_ms(::google::protobuf::int64 value);

  // bool use_filtered_first_solution_strategy = 2;
  void clear_use_filtered_first_solution_strategy();
  static const int kUseFilteredFirstSolutionStrategyFieldNumber = 2;
  bool use_filtered_first_solution_strategy() const;
  void set_use_filtered_first_solution_strategy(bool value);

  // bool savings_add_reverse_arcs = 15;
  void clear_savings_add_reverse_arcs();
  static const int kSavingsAddReverseArcsFieldNumber = 15;
  bool savings_add_reverse_arcs() const;
  void set_savings_add_reverse_arcs(bool value);

  // bool use_depth_first_search = 6;
  void clear_use_depth_first_search();
  static const int kUseDepthFirstSearchFieldNumber = 6;
  bool use_depth_first_search() const;
  void set_use_depth_first_search(bool value);

  // bool use_light_propagation = 11;
  void clear_use_light_propagation();
  static const int kUseLightPropagationFieldNumber = 11;
  bool use_light_propagation() const;
  void set_use_light_propagation(bool value);

  // bool fingerprint_arc_cost_evaluators = 12;
  void clear_fingerprint_arc_cost_evaluators();
  static const int kFingerprintArcCostEvaluatorsFieldNumber = 12;
  bool fingerprint_arc_cost_evaluators() const;
  void set_fingerprint_arc_cost_evaluators(bool value);

  // bool log_search = 13;
  void clear_log_search();
  static const int kLogSearchFieldNumber = 13;
  bool log_search() const;
  void set_log_search(bool value);

  // int64 lns_time_limit_ms = 10;
  void clear_lns_time_limit_ms();
  static const int kLnsTimeLimitMsFieldNumber = 10;
  ::google::protobuf::int64 lns_time_limit_ms() const;
  void set_lns_time_limit_ms(::google::protobuf::int64 value);

  // double savings_neighbors_ratio = 14;
  void clear_savings_neighbors_ratio();
  static const int kSavingsNeighborsRatioFieldNumber = 14;
  double savings_neighbors_ratio() const;
  void set_savings_neighbors_ratio(double value);

  // @@protoc_insertion_point(class_scope:operations_research.RoutingSearchParameters)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* local_search_operators_;
  int first_solution_strategy_;
  int local_search_metaheuristic_;
  double guided_local_search_lambda_coefficient_;
  ::google::protobuf::int64 optimization_step_;
  ::google::protobuf::int64 solution_limit_;
  ::google::protobuf::int64 time_limit_ms_;
  bool use_filtered_first_solution_strategy_;
  bool savings_add_reverse_arcs_;
  bool use_depth_first_search_;
  bool use_light_propagation_;
  bool fingerprint_arc_cost_evaluators_;
  bool log_search_;
  ::google::protobuf::int64 lns_time_limit_ms_;
  double savings_neighbors_ratio_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class RoutingModelParameters : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:operations_research.RoutingModelParameters) */ {
 public:
  RoutingModelParameters();
  virtual ~RoutingModelParameters();

  RoutingModelParameters(const RoutingModelParameters& from);

  inline RoutingModelParameters& operator=(const RoutingModelParameters& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoutingModelParameters(RoutingModelParameters&& from) noexcept
    : RoutingModelParameters() {
    *this = ::std::move(from);
  }

  inline RoutingModelParameters& operator=(RoutingModelParameters&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingModelParameters& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoutingModelParameters* internal_default_instance() {
    return reinterpret_cast<const RoutingModelParameters*>(
               &_RoutingModelParameters_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(RoutingModelParameters* other);
  friend void swap(RoutingModelParameters& a, RoutingModelParameters& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoutingModelParameters* New() const final {
    return CreateMaybeMessage<RoutingModelParameters>(NULL);
  }

  RoutingModelParameters* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<RoutingModelParameters>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const RoutingModelParameters& from);
  void MergeFrom(const RoutingModelParameters& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoutingModelParameters* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .operations_research.ConstraintSolverParameters solver_parameters = 1;
  bool has_solver_parameters() const;
  void clear_solver_parameters();
  static const int kSolverParametersFieldNumber = 1;
  private:
  const ::operations_research::ConstraintSolverParameters& _internal_solver_parameters() const;
  public:
  const ::operations_research::ConstraintSolverParameters& solver_parameters() const;
  ::operations_research::ConstraintSolverParameters* release_solver_parameters();
  ::operations_research::ConstraintSolverParameters* mutable_solver_parameters();
  void set_allocated_solver_parameters(::operations_research::ConstraintSolverParameters* solver_parameters);

  // bool reduce_vehicle_cost_model = 2;
  void clear_reduce_vehicle_cost_model();
  static const int kReduceVehicleCostModelFieldNumber = 2;
  bool reduce_vehicle_cost_model() const;
  void set_reduce_vehicle_cost_model(bool value);

  // int32 max_callback_cache_size = 3;
  void clear_max_callback_cache_size();
  static const int kMaxCallbackCacheSizeFieldNumber = 3;
  ::google::protobuf::int32 max_callback_cache_size() const;
  void set_max_callback_cache_size(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:operations_research.RoutingModelParameters)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::operations_research::ConstraintSolverParameters* solver_parameters_;
  bool reduce_vehicle_cost_model_;
  ::google::protobuf::int32 max_callback_cache_size_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoutingSearchParameters_LocalSearchNeighborhoodOperators

// bool use_relocate = 1;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_relocate() {
  use_relocate_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_relocate() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate)
  return use_relocate_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_relocate(bool value) {
  
  use_relocate_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate)
}

// bool use_relocate_pair = 2;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_relocate_pair() {
  use_relocate_pair_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_relocate_pair() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_pair)
  return use_relocate_pair_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_relocate_pair(bool value) {
  
  use_relocate_pair_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_pair)
}

// bool use_relocate_neighbors = 3;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_relocate_neighbors() {
  use_relocate_neighbors_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_relocate_neighbors() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_neighbors)
  return use_relocate_neighbors_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_relocate_neighbors(bool value) {
  
  use_relocate_neighbors_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_neighbors)
}

// bool use_exchange = 4;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_exchange() {
  use_exchange_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_exchange() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_exchange)
  return use_exchange_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_exchange(bool value) {
  
  use_exchange_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_exchange)
}

// bool use_cross = 5;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_cross() {
  use_cross_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_cross() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_cross)
  return use_cross_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_cross(bool value) {
  
  use_cross_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_cross)
}

// bool use_cross_exchange = 6;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_cross_exchange() {
  use_cross_exchange_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_cross_exchange() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_cross_exchange)
  return use_cross_exchange_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_cross_exchange(bool value) {
  
  use_cross_exchange_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_cross_exchange)
}

// bool use_two_opt = 7;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_two_opt() {
  use_two_opt_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_two_opt() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_two_opt)
  return use_two_opt_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_two_opt(bool value) {
  
  use_two_opt_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_two_opt)
}

// bool use_or_opt = 8;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_or_opt() {
  use_or_opt_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_or_opt() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_or_opt)
  return use_or_opt_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_or_opt(bool value) {
  
  use_or_opt_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_or_opt)
}

// bool use_lin_kernighan = 9;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_lin_kernighan() {
  use_lin_kernighan_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_lin_kernighan() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_lin_kernighan)
  return use_lin_kernighan_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_lin_kernighan(bool value) {
  
  use_lin_kernighan_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_lin_kernighan)
}

// bool use_tsp_opt = 10;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_tsp_opt() {
  use_tsp_opt_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_tsp_opt() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_tsp_opt)
  return use_tsp_opt_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_tsp_opt(bool value) {
  
  use_tsp_opt_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_tsp_opt)
}

// bool use_make_active = 11;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_make_active() {
  use_make_active_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_make_active() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_active)
  return use_make_active_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_make_active(bool value) {
  
  use_make_active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_active)
}

// bool use_relocate_and_make_active = 21;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_relocate_and_make_active() {
  use_relocate_and_make_active_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_relocate_and_make_active() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_and_make_active)
  return use_relocate_and_make_active_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_relocate_and_make_active(bool value) {
  
  use_relocate_and_make_active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_relocate_and_make_active)
}

// bool use_make_inactive = 12;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_make_inactive() {
  use_make_inactive_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_make_inactive() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_inactive)
  return use_make_inactive_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_make_inactive(bool value) {
  
  use_make_inactive_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_inactive)
}

// bool use_make_chain_inactive = 13;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_make_chain_inactive() {
  use_make_chain_inactive_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_make_chain_inactive() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_chain_inactive)
  return use_make_chain_inactive_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_make_chain_inactive(bool value) {
  
  use_make_chain_inactive_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_make_chain_inactive)
}

// bool use_swap_active = 14;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_swap_active() {
  use_swap_active_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_swap_active() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_swap_active)
  return use_swap_active_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_swap_active(bool value) {
  
  use_swap_active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_swap_active)
}

// bool use_extended_swap_active = 15;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_extended_swap_active() {
  use_extended_swap_active_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_extended_swap_active() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_extended_swap_active)
  return use_extended_swap_active_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_extended_swap_active(bool value) {
  
  use_extended_swap_active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_extended_swap_active)
}

// bool use_node_pair_swap_active = 20;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_node_pair_swap_active() {
  use_node_pair_swap_active_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_node_pair_swap_active() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_node_pair_swap_active)
  return use_node_pair_swap_active_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_node_pair_swap_active(bool value) {
  
  use_node_pair_swap_active_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_node_pair_swap_active)
}

// bool use_path_lns = 16;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_path_lns() {
  use_path_lns_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_path_lns() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_path_lns)
  return use_path_lns_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_path_lns(bool value) {
  
  use_path_lns_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_path_lns)
}

// bool use_full_path_lns = 17;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_full_path_lns() {
  use_full_path_lns_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_full_path_lns() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_full_path_lns)
  return use_full_path_lns_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_full_path_lns(bool value) {
  
  use_full_path_lns_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_full_path_lns)
}

// bool use_tsp_lns = 18;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_tsp_lns() {
  use_tsp_lns_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_tsp_lns() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_tsp_lns)
  return use_tsp_lns_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_tsp_lns(bool value) {
  
  use_tsp_lns_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_tsp_lns)
}

// bool use_inactive_lns = 19;
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::clear_use_inactive_lns() {
  use_inactive_lns_ = false;
}
inline bool RoutingSearchParameters_LocalSearchNeighborhoodOperators::use_inactive_lns() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_inactive_lns)
  return use_inactive_lns_;
}
inline void RoutingSearchParameters_LocalSearchNeighborhoodOperators::set_use_inactive_lns(bool value) {
  
  use_inactive_lns_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators.use_inactive_lns)
}

// -------------------------------------------------------------------

// RoutingSearchParameters

// .operations_research.FirstSolutionStrategy.Value first_solution_strategy = 1;
inline void RoutingSearchParameters::clear_first_solution_strategy() {
  first_solution_strategy_ = 0;
}
inline ::operations_research::FirstSolutionStrategy_Value RoutingSearchParameters::first_solution_strategy() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.first_solution_strategy)
  return static_cast< ::operations_research::FirstSolutionStrategy_Value >(first_solution_strategy_);
}
inline void RoutingSearchParameters::set_first_solution_strategy(::operations_research::FirstSolutionStrategy_Value value) {
  
  first_solution_strategy_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.first_solution_strategy)
}

// bool use_filtered_first_solution_strategy = 2;
inline void RoutingSearchParameters::clear_use_filtered_first_solution_strategy() {
  use_filtered_first_solution_strategy_ = false;
}
inline bool RoutingSearchParameters::use_filtered_first_solution_strategy() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.use_filtered_first_solution_strategy)
  return use_filtered_first_solution_strategy_;
}
inline void RoutingSearchParameters::set_use_filtered_first_solution_strategy(bool value) {
  
  use_filtered_first_solution_strategy_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.use_filtered_first_solution_strategy)
}

// double savings_neighbors_ratio = 14;
inline void RoutingSearchParameters::clear_savings_neighbors_ratio() {
  savings_neighbors_ratio_ = 0;
}
inline double RoutingSearchParameters::savings_neighbors_ratio() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.savings_neighbors_ratio)
  return savings_neighbors_ratio_;
}
inline void RoutingSearchParameters::set_savings_neighbors_ratio(double value) {
  
  savings_neighbors_ratio_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.savings_neighbors_ratio)
}

// bool savings_add_reverse_arcs = 15;
inline void RoutingSearchParameters::clear_savings_add_reverse_arcs() {
  savings_add_reverse_arcs_ = false;
}
inline bool RoutingSearchParameters::savings_add_reverse_arcs() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.savings_add_reverse_arcs)
  return savings_add_reverse_arcs_;
}
inline void RoutingSearchParameters::set_savings_add_reverse_arcs(bool value) {
  
  savings_add_reverse_arcs_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.savings_add_reverse_arcs)
}

// .operations_research.RoutingSearchParameters.LocalSearchNeighborhoodOperators local_search_operators = 3;
inline bool RoutingSearchParameters::has_local_search_operators() const {
  return this != internal_default_instance() && local_search_operators_ != NULL;
}
inline void RoutingSearchParameters::clear_local_search_operators() {
  if (GetArenaNoVirtual() == NULL && local_search_operators_ != NULL) {
    delete local_search_operators_;
  }
  local_search_operators_ = NULL;
}
inline const ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators& RoutingSearchParameters::_internal_local_search_operators() const {
  return *local_search_operators_;
}
inline const ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators& RoutingSearchParameters::local_search_operators() const {
  const ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* p = local_search_operators_;
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.local_search_operators)
  return p != NULL ? *p : *reinterpret_cast<const ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators*>(
      &::operations_research::_RoutingSearchParameters_LocalSearchNeighborhoodOperators_default_instance_);
}
inline ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* RoutingSearchParameters::release_local_search_operators() {
  // @@protoc_insertion_point(field_release:operations_research.RoutingSearchParameters.local_search_operators)
  
  ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* temp = local_search_operators_;
  local_search_operators_ = NULL;
  return temp;
}
inline ::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* RoutingSearchParameters::mutable_local_search_operators() {
  
  if (local_search_operators_ == NULL) {
    auto* p = CreateMaybeMessage<::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators>(GetArenaNoVirtual());
    local_search_operators_ = p;
  }
  // @@protoc_insertion_point(field_mutable:operations_research.RoutingSearchParameters.local_search_operators)
  return local_search_operators_;
}
inline void RoutingSearchParameters::set_allocated_local_search_operators(::operations_research::RoutingSearchParameters_LocalSearchNeighborhoodOperators* local_search_operators) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete local_search_operators_;
  }
  if (local_search_operators) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      local_search_operators = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, local_search_operators, submessage_arena);
    }
    
  } else {
    
  }
  local_search_operators_ = local_search_operators;
  // @@protoc_insertion_point(field_set_allocated:operations_research.RoutingSearchParameters.local_search_operators)
}

// .operations_research.LocalSearchMetaheuristic.Value local_search_metaheuristic = 4;
inline void RoutingSearchParameters::clear_local_search_metaheuristic() {
  local_search_metaheuristic_ = 0;
}
inline ::operations_research::LocalSearchMetaheuristic_Value RoutingSearchParameters::local_search_metaheuristic() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.local_search_metaheuristic)
  return static_cast< ::operations_research::LocalSearchMetaheuristic_Value >(local_search_metaheuristic_);
}
inline void RoutingSearchParameters::set_local_search_metaheuristic(::operations_research::LocalSearchMetaheuristic_Value value) {
  
  local_search_metaheuristic_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.local_search_metaheuristic)
}

// double guided_local_search_lambda_coefficient = 5;
inline void RoutingSearchParameters::clear_guided_local_search_lambda_coefficient() {
  guided_local_search_lambda_coefficient_ = 0;
}
inline double RoutingSearchParameters::guided_local_search_lambda_coefficient() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.guided_local_search_lambda_coefficient)
  return guided_local_search_lambda_coefficient_;
}
inline void RoutingSearchParameters::set_guided_local_search_lambda_coefficient(double value) {
  
  guided_local_search_lambda_coefficient_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.guided_local_search_lambda_coefficient)
}

// bool use_depth_first_search = 6;
inline void RoutingSearchParameters::clear_use_depth_first_search() {
  use_depth_first_search_ = false;
}
inline bool RoutingSearchParameters::use_depth_first_search() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.use_depth_first_search)
  return use_depth_first_search_;
}
inline void RoutingSearchParameters::set_use_depth_first_search(bool value) {
  
  use_depth_first_search_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.use_depth_first_search)
}

// int64 optimization_step = 7;
inline void RoutingSearchParameters::clear_optimization_step() {
  optimization_step_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RoutingSearchParameters::optimization_step() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.optimization_step)
  return optimization_step_;
}
inline void RoutingSearchParameters::set_optimization_step(::google::protobuf::int64 value) {
  
  optimization_step_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.optimization_step)
}

// int64 solution_limit = 8;
inline void RoutingSearchParameters::clear_solution_limit() {
  solution_limit_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RoutingSearchParameters::solution_limit() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.solution_limit)
  return solution_limit_;
}
inline void RoutingSearchParameters::set_solution_limit(::google::protobuf::int64 value) {
  
  solution_limit_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.solution_limit)
}

// int64 time_limit_ms = 9;
inline void RoutingSearchParameters::clear_time_limit_ms() {
  time_limit_ms_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RoutingSearchParameters::time_limit_ms() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.time_limit_ms)
  return time_limit_ms_;
}
inline void RoutingSearchParameters::set_time_limit_ms(::google::protobuf::int64 value) {
  
  time_limit_ms_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.time_limit_ms)
}

// int64 lns_time_limit_ms = 10;
inline void RoutingSearchParameters::clear_lns_time_limit_ms() {
  lns_time_limit_ms_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RoutingSearchParameters::lns_time_limit_ms() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.lns_time_limit_ms)
  return lns_time_limit_ms_;
}
inline void RoutingSearchParameters::set_lns_time_limit_ms(::google::protobuf::int64 value) {
  
  lns_time_limit_ms_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.lns_time_limit_ms)
}

// bool use_light_propagation = 11;
inline void RoutingSearchParameters::clear_use_light_propagation() {
  use_light_propagation_ = false;
}
inline bool RoutingSearchParameters::use_light_propagation() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.use_light_propagation)
  return use_light_propagation_;
}
inline void RoutingSearchParameters::set_use_light_propagation(bool value) {
  
  use_light_propagation_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.use_light_propagation)
}

// bool fingerprint_arc_cost_evaluators = 12;
inline void RoutingSearchParameters::clear_fingerprint_arc_cost_evaluators() {
  fingerprint_arc_cost_evaluators_ = false;
}
inline bool RoutingSearchParameters::fingerprint_arc_cost_evaluators() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.fingerprint_arc_cost_evaluators)
  return fingerprint_arc_cost_evaluators_;
}
inline void RoutingSearchParameters::set_fingerprint_arc_cost_evaluators(bool value) {
  
  fingerprint_arc_cost_evaluators_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.fingerprint_arc_cost_evaluators)
}

// bool log_search = 13;
inline void RoutingSearchParameters::clear_log_search() {
  log_search_ = false;
}
inline bool RoutingSearchParameters::log_search() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingSearchParameters.log_search)
  return log_search_;
}
inline void RoutingSearchParameters::set_log_search(bool value) {
  
  log_search_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingSearchParameters.log_search)
}

// -------------------------------------------------------------------

// RoutingModelParameters

// .operations_research.ConstraintSolverParameters solver_parameters = 1;
inline bool RoutingModelParameters::has_solver_parameters() const {
  return this != internal_default_instance() && solver_parameters_ != NULL;
}
inline const ::operations_research::ConstraintSolverParameters& RoutingModelParameters::_internal_solver_parameters() const {
  return *solver_parameters_;
}
inline const ::operations_research::ConstraintSolverParameters& RoutingModelParameters::solver_parameters() const {
  const ::operations_research::ConstraintSolverParameters* p = solver_parameters_;
  // @@protoc_insertion_point(field_get:operations_research.RoutingModelParameters.solver_parameters)
  return p != NULL ? *p : *reinterpret_cast<const ::operations_research::ConstraintSolverParameters*>(
      &::operations_research::_ConstraintSolverParameters_default_instance_);
}
inline ::operations_research::ConstraintSolverParameters* RoutingModelParameters::release_solver_parameters() {
  // @@protoc_insertion_point(field_release:operations_research.RoutingModelParameters.solver_parameters)
  
  ::operations_research::ConstraintSolverParameters* temp = solver_parameters_;
  solver_parameters_ = NULL;
  return temp;
}
inline ::operations_research::ConstraintSolverParameters* RoutingModelParameters::mutable_solver_parameters() {
  
  if (solver_parameters_ == NULL) {
    auto* p = CreateMaybeMessage<::operations_research::ConstraintSolverParameters>(GetArenaNoVirtual());
    solver_parameters_ = p;
  }
  // @@protoc_insertion_point(field_mutable:operations_research.RoutingModelParameters.solver_parameters)
  return solver_parameters_;
}
inline void RoutingModelParameters::set_allocated_solver_parameters(::operations_research::ConstraintSolverParameters* solver_parameters) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(solver_parameters_);
  }
  if (solver_parameters) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      solver_parameters = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, solver_parameters, submessage_arena);
    }
    
  } else {
    
  }
  solver_parameters_ = solver_parameters;
  // @@protoc_insertion_point(field_set_allocated:operations_research.RoutingModelParameters.solver_parameters)
}

// bool reduce_vehicle_cost_model = 2;
inline void RoutingModelParameters::clear_reduce_vehicle_cost_model() {
  reduce_vehicle_cost_model_ = false;
}
inline bool RoutingModelParameters::reduce_vehicle_cost_model() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingModelParameters.reduce_vehicle_cost_model)
  return reduce_vehicle_cost_model_;
}
inline void RoutingModelParameters::set_reduce_vehicle_cost_model(bool value) {
  
  reduce_vehicle_cost_model_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingModelParameters.reduce_vehicle_cost_model)
}

// int32 max_callback_cache_size = 3;
inline void RoutingModelParameters::clear_max_callback_cache_size() {
  max_callback_cache_size_ = 0;
}
inline ::google::protobuf::int32 RoutingModelParameters::max_callback_cache_size() const {
  // @@protoc_insertion_point(field_get:operations_research.RoutingModelParameters.max_callback_cache_size)
  return max_callback_cache_size_;
}
inline void RoutingModelParameters::set_max_callback_cache_size(::google::protobuf::int32 value) {
  
  max_callback_cache_size_ = value;
  // @@protoc_insertion_point(field_set:operations_research.RoutingModelParameters.max_callback_cache_size)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace operations_research

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ortools_2fconstraint_5fsolver_2frouting_5fparameters_2eproto
